CameraPose_Photon:
  motion_module:
    - "models/Motion_Module/CameraMotion.ckpt"
  
  dreambooth_path: "models/DreamBooth_LoRA/photon_v1.safetensors"
  lora_model_path: ""
  
  seed:           [695978744, 2622728552283679005, 7422206404404924000, 1139238851, 15720551683056146389]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "A majestic castle floating in the clouds, surrounded by vibrant rainbows,"
    - "fireworks, scenery, sky, outdoors, city, night, building, people, crowd, cloud, castle, tower, aerial fireworks, night sky, (illustration:1.0), masterpiece, best quality, "
    - "Grand tree exploding to neon dust in a cinematic fantasy landscape, surreal breathtaking magical forest, flowing river, reflection, bioluminescent mushrooms, centered on image, negative space, intricate details, vibrant colors, 8k, ultra-detailed, full moon night, perfect composition, Rule of Thirds"
    - "An enigmatic door awaits at the end of a winding path, adorned with overgrown vines and emanating an otherworldly glow. stone road, blurry, fantasy, epic"
    - "Cinematic, intricate, snowy night, landscape, mountains, mountain cabin, cozy, starry sky, northern lights"
  
  n_prompt:
    - "cartoon, painting, illustration, (worst quality, low quality, normal quality:2)"
    - "cartoon, painting, illustration, (worst quality, low quality, normal quality:2)"
    - "cartoon, painting, illustration, (worst quality, low quality, normal quality:2)"
    - "cartoon, painting, illustration, (worst quality, low quality, normal quality:2)"
    - "cartoon, painting, illustration, (worst quality, low quality, normal quality:2)"
  
  post_prompt: ''

  pose_folds:
    - "cus_camera_motion/test_camera_I_3.0x.json"
    - "cus_camera_motion/test_camera_U_3.0x.json"
    - "cus_camera_motion/test_camera_D_3.0x.json"
    - "cus_camera_motion/test_camera_O_3.0x.json"
    - "cus_camera_motion/test_camera_L_3.0x.json"
    - "cus_camera_motion/test_camera_R_3.0x.json"
    - "cus_camera_motion/test_camera_Round-RI.json"
    - "cus_camera_motion/test_camera_Round-ZoomIn.json"
    - "cus_camera_motion/test_camera_SPIN-CW.json"
    - "cus_camera_motion/test_camera_SPIN-ACW.json"
    - "cus_camera_motion/test_camera_SPIN-DU.json"
    - "cus_camera_motion/test_camera_SPIN-LR.json"
    - "cus_camera_motion/test_camera_SPIN-ACW_120.json"
    - "cus_camera_motion/test_camera_SPIN-ACW_150.json"
    - "cus_camera_motion/test_camera_SPIN-CW_120.json"
    - "cus_camera_motion/test_camera_SPIN-CW_150.json"


    
